language: d
env:
  global:
    secure: DXuSnGg2UgnG653rGeqIm2EOeLitKpq98rkmIiGbVdooqZX292ZZGTpB9tdLcu3+918vAMUt3wUNIskHT8F8ubNaqdp8/jzQAt2i/9cWm2MJcOAFSPqyY5ldmLggTPdSza91UJQ5s1/GspzmzROjrey7kjcn00uVDnm6OvoqiAk=
install:
- sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O
  /etc/apt/sources.list.d/d-apt.list
- sudo apt-get update
- sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
- sudo apt-get update
- sudo apt-get install dmd-bin dub
- sudo dub fetch x11
- sudo cp empty-game/libawesomium-1.6.5.so /usr/lib/libawesomium-1.6.5.so.0
script:
- sudo dub test -q
- sudo dub build --force
- sudo ./dash create ../test-create
- sudo ./dash compress ../test-create
- sudo ./dash publish ../test-create
after_success:
- zip -r empty-game.zip empty-game
- zip -r dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip dash empty-game.zip
- sudo bash ./.travis/github-release.sh "$TRAVIS_REPO_SLUG" "`git describe`" dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
