language: d
env:
  global:
    secure: DXuSnGg2UgnG653rGeqIm2EOeLitKpq98rkmIiGbVdooqZX292ZZGTpB9tdLcu3+918vAMUt3wUNIskHT8F8ubNaqdp8/jzQAt2i/9cWm2MJcOAFSPqyY5ldmLggTPdSza91UJQ5s1/GspzmzROjrey7kjcn00uVDnm6OvoqiAk=
install:
- sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O
  /etc/apt/sources.list.d/d-apt.list
- sudo apt-get update
- sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
- sudo apt-get update
- sudo apt-get install dmd-bin dub libfreeimage-dev libjpeg62-dev
- sudo dub fetch x11
script:
- sudo dub test -q
- sudo dub build --force
- sudo ./bin/dash create ../test-create
- sudo ./bin/dash compress ../test-create
- sudo ./bin/dash publish ../test-create
after_success:
- zip -r dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip ./bin/dash ./bin/empty-game.zip
- sudo bash ./.travis/github-release.sh "$TRAVIS_REPO_SLUG" "`git describe`" dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
