language: d
env:
- DMD_VER=2.066.0 DUB_VER=0.9.21
  global:
    secure: DXuSnGg2UgnG653rGeqIm2EOeLitKpq98rkmIiGbVdooqZX292ZZGTpB9tdLcu3+918vAMUt3wUNIskHT8F8ubNaqdp8/jzQAt2i/9cWm2MJcOAFSPqyY5ldmLggTPdSza91UJQ5s1/GspzmzROjrey7kjcn00uVDnm6OvoqiAk=
install:
- # Install DMD
- DMD_DEB=dmd_${DMD_VER}-0_amd64.deb
- wget ftp://ftp.dlang.org/${DMD_DEB}
- sudo dpkg -i ${DMD_DEB} || true
- sudo apt-get update
- sudo apt-get install -f
- sudo dpkg -i ${DMD_DEB}
# Install dub
- DUB_TAR=dub-${DUB_VER}-${TRAVIS_OS_NAME}-x86_64.tar.gz
- wget http://code.dlang.org/files/${DUB_TAR}
- sudo tar -C /usr/local/bin -zxf ${DUB_TAR}
# Install x11
- sudo dub fetch x11
# Install system dependencies
- sudo apt-get install libfreeimage-dev libjpeg62-dev
script:
- sudo dub test -q
- sudo dub build --force
- sudo ./bin/dash create ../test-create
- sudo ./bin/dash compress ../test-create
- sudo ./bin/dash publish ../test-create
after_success: zip -r dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip ./bin/dash ./bin/empty-game.zip
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89d5205a2483bcd72a32
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ef8tYoL5bdEfHwzJOo5GJoxygsQwB1whwTdyyzUhyrYn2J0/lgBkCY4NDn3nmZan0tgsMbg2rO2bCurq1pBZ8GMbV3YOo+EHq78xra2m81Kl67sOc8fvMnJ2Ao2NUR7ZbLoONxQYN7geg6jPkr3NFkyrNHyUUF8YXUBFFy5DdPU=
  file: dash-cli-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip
  on:
    tags: true
    all_branches: true
    repo: Circular-Studios/Dash-CLI
